### PR TITLE
Fixed callback memleaks and updated .travis.yml

### PR DESCRIPTION
**Pull request by yupferris**
And a typo :)

### CODE REVIEW

**Comment by yupferris** [comment]
The errors in the failing CI build seem to all be in coreaudio-sys-0.1.1 against rust 1.0.0-beta. Was this a problem before now? I'm not entirely sure why this would break now.

**Comment by yupferris** [comment]
One such error, for instance, comes from this line specifically:
https://github.com/RustAudio/coreaudio-sys/blob/master/src/audio_unit.rs#L91

This appears to be a problem with coreaudio-sys against rust 1.0.0-beta, not a problem with the code in this repository.

**Comment by mitchmindtree** [comment]
Awesome, thanks a lot for this!

As the callback is owned via the `*mut` I think it still gets leaked when `AudioUnit` is dropped. I think we still need to free it during the `AudioUnit`'s `Drop` implementation - something like:

```Rust
free(self.callback as *mut c_void)
```

Don't worry about the 1.0.0-beta breaking - it was around that period I was last working on this crate. The `.travis.yml` should probably just be changed to run on the latest `stable` and `nightly` builds.

**Comment by mitchmindtree** [comment]
There's an example of using free with the FFI [here](http://smallcultfollowing.com/rust-int-variations/isize-usize/guide-unsafe.html#making-the-unsafe-safe(r)).

**Comment by yupferris** [comment]
It will not get leaked, as transmute'ing back to the Box type will give the new binding ownership, so it will be dropped properly when the binding goes out of scope. These lines take care of this, both when the AudioUnit is being dropped and also if the callback is set multiple times on the builder (which the API allows):
https://github.com/yupferris/coreaudio-rs/commit/fe17b74f6756e2627198878ab8a098e96e566e3e#diff-0e06b6ac659ae37f8967747b5109ed4aR178
https://github.com/yupferris/coreaudio-rs/commit/fe17b74f6756e2627198878ab8a098e96e566e3e#diff-0e06b6ac659ae37f8967747b5109ed4aR201

I've tested this locally with the following pieces of code (outputs at the bottom of the gists):
https://gist.github.com/yupferris/d1502d1f3f76938c3d48
https://gist.github.com/yupferris/036c798c15411695faff

And also the isolated case:
https://gist.github.com/yupferris/c706f24de797f0bc949f

Note that in all these cases, without transmute'ing back to the Box type, it DOES leak as expected. I've also verified this with both debug/release builds with all cases.

Interestingly, I did also try `free` as you suggested, because I wasn't sure if it would work the same way. This is the isolated case and its result:
https://gist.github.com/yupferris/c706f24de797f0bc949f

In this case the allocator complains about the pointer not having been allocated, and the resource isn't dropped properly. I don't know 100% why this is the case, but from my experience in C/C++ generally it's a bad idea to use `free` with anything that hasn't been `new`'d, for instance `free`'ing a pointer that was created just with `malloc`, as they're not guaranteed to be implemented symmetrically. I'm guessing that's also the case here; `free` likely will simply try to free the memory from the heap allocator `malloc` uses, and transmute'ing back to the Box type and letting the binding fall out of scope will drop the resource properly.

This has been a very very interesting test case and quite fun to play with :D

**Comment by yupferris** [comment]
I'll have a look at updating the travis config next.

**Comment by yupferris** [comment]
All green :)

**Comment by mitchmindtree** [comment]
Ahhh of course! My apologies, for some reason I didn't notice the addition you'd made to the Drop implementation (I guess I was caught up expecting to see free somewhere, but simply transferring ownership back with transmute makes sense)!

Thanks a lot for both the leak and travis fixes, great stuff :+1:

**Comment by mitchmindtree** [comment]
Just added some comments and published this to crates.io under 0.1.1 [here](https://github.com/RustAudio/coreaudio-rs/pull/9) :smile_cat:

**Comment by yupferris** [comment]
woo! \o/ :)

**Pull request merged**
