### PR TITLE
CI Improvements - GitHub workflow, make docs.rs default to macos

### PR DESCRIPTION
**Pull request by mitchmindtree**
This is a follow-up to RustAudio/coreaudio-sys#37.

- Checks more cargo feature permutations.
- Adds an auto-publishing action.
- Makes sure docs.rs defaults to macos build.
- Refers users to docs.rs for docs on readme rather than rustaudio.github.io.
- Removes old travis CI.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
I think this should probably wait to land until we can work out how to solve RustAudio/coreaudio-sys#40.

**Comment by MichaelHills** [comment]
@mitchmindtree it would be nice to get the auto-publish going. I'm trying to find some free time to finish off my cpal iOS support, so will want to publish `coreaudio-rs` soon.

I don't fully understand the docs.rs issue in that, does it currently work with the travis flow but not github CI or something like that? Would it be possible to have both travis + github CI to land just the auto-publishing part?

**Comment by mitchmindtree** [comment]
Thanks for the reminder about this @MichaelHills!

Yeah so far the blocker is this cross-compilation step necessary to get the documentation building in the docs.rs workflow. See here https://github.com/RustAudio/coreaudio-sys/pull/38. I don't quite remember how far I got with it or why that current PR is failing.

I think it wouldn't be so bad if we landed this auto-publishing change in the meantime, as the current `coreaudio-rs` docs.rs documentation is useless anyway (it's a Linux build of a macOS framework). We can always get #38 working afterwords, and in the meantime users should be able to build the docs locally on macos with `cargo doc --open`.

**Comment by MichaelHills** [comment]
Ah I see, I might take a look into the cross-compilation thing after landing the cpal ios PR.

**Pull request merged**
