### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by MichaelHills**
- dyn trait
- try!
- mem::uninitialized

Not sure if I'm doing this right. macOS feedback example still runs though.

### CODE REVIEW

**Review by simlay — APPROVED** [review]
If I read this right, the following can kinda be summarized with:
* [`try`](https://doc.rust-lang.org/std/macro.try.html) is depricated at 1.39,
* [`dyn trait` added in 1.27 with deprication](https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html) with [warning around 1.37?](https://github.com/stepancheg/rust-protobuf/issues/414)
* [`std::error::Error` trait depricates `description` function in place of `impl Display`](https://doc.rust-lang.org/std/error/trait.Error.html#method.description)
* [Replace `std::mem::uninitialized` with `std::mem::MaybeUninit`](https://doc.rust-lang.org/std/mem/fn.uninitialized.html)

**Comment by MichaelHills** [comment]
That’s correct. Hmm is there a less invasive alternative I could have done for the Error description() change to use to_string() instead of changing the implementation of Display? Is it just replacing description with to_string?

**Comment by simlay** [comment]
> That’s correct. Hmm is there a less invasive alternative I could have done for the Error description() change to use to_string() instead of changing the implementation of Display? Is it just replacing description with to_string?

I think this is okay. I'm not entirely sure what the documentation means with `to_string` (maybe `impl String::from`) but this seems okay to me.

**Comment by MichaelHills** [comment]
Did further testing, forcing some errors out, seems like if main() returns Result, it'll log crashes with debug and not display. So I wrapped main to print the display string and it works for a couple of different errors I forced.

Still works on mac feedback + sine and iOS feedback.

**Pull request merged**
