### PR TITLE
Implement proper handling of AudioFormat in `set_render_callback`

### LINKED ISSUE #10: Try and remove `Box`ing wherever possible within the render_callback builder method.
There's a lot of boxing going on - all of which should be theoretically unnecessary given that we're sharing the stack with the C code, not sending stuff to it.

It might be easier to address this once the Fn/FnMut/FnOnce trait implementations are stabilised.

### LINKED ISSUE #11: Remove unnecessary Vec allocation in `extern "C" fn input_proc`
There should definitely be no allocations occurring in the realtime audio callback.

It should be possible to change [this array of channels](https://github.com/RustAudio/coreaudio-rs/blob/master/src/audio_unit/mod.rs#L276) from a Vec to a slice, using `from_raw_parts_mut` instead.

### LINKED ISSUE #12: Add proper support for handling different sample types and stream formats at runtime.
My favourite solution to this is using something like [CPAL's UnknownTypeBuffer](https://github.com/tomaka/cpal/blob/master/src/lib.rs#L185) has an intermediary.

### PR DESCRIPTION
**Pull request by mitchmindtree**
~~**WIP - Do not merge**~~

Closes #10 
Closes #11 
Closes #12 (will open up a new issue for implementing this in a proper type-safe manner down the track)

Makes it possible to fix [this](https://github.com/tomaka/cpal/issues/52).

### CODE REVIEW

**Comment by mitchmindtree** [comment]
@yupferris aiight. I think this is at least a big improvement over the old callback story!

The `set_render_callback` function argument is now un-boxed and takes a `render_callback::Args<D>` as its argument type, where `D` is some `Data` type compatible with the audio unit's stream format. Currently, `Data` is only implemented for 3 types:
- `Interleaved<'a, S>`: a wrapper around a linear PCM buffer of interleaved samples.
- `NonInterleaved<'a, S>`: a wrapper around a linear PCM buffer of non-interleaved samples.
- `Raw`: a raw pointer to the `AudioBufferList` given by Core Audio, allowing the user to handle the typification themselves.

Handling different sample formats is still a bit shady however... I'm realising that we're not going to get proper type safety around audio unit subtype-specific AudioFormat stuff until we turn all the `type.rs` enums into actual types, and then associate compatible render callback args and audio format types with each (which will be a mission).

For now, i'm ok with returning an `Err` from `set_render_callback` at run-time for incompatible render_callback args or sample formats. I just don't have the time right now to comb through audio unit framework docs and do all the necessary typification to get things totally type-safe :(

Also, I haven't actually tested anything other than `f32` samples yet as we're using one of the device output audio units in the example (`DefaultOutput` which is basically the default `HalOutput`) and I believe these audio units might only be compatible with the platform's canonical formats,

>   The canonical formats in Core Audio are as follows:
>
> - iOS input and output: Linear PCM with 16-bit integer samples.
> - iOS audio units and other audio processing: Noninterleaved linear PCM with 8.24-bit fixed-point samples
> - Mac input and output: Linear PCM with 32-bit floating point samples.
> - Mac audio units and other audio processing: Noninterleaved linear PCM with 32-bit floating-point

We should look into setting up some more examples that use the other audio_unit types (perhaps one for each) so that we can test (and demonstrate) their behaviour a little more easily. I think we might have to set up some intermediary audio unit (`GenericOutput` perhaps?) before the device output audio unit in order to be able to test different formats properly. I currently don't know how to connect audio units together though - i'm guessing it has something to do with the audio unit Graph API (which we don't yet support).

**Comment by mitchmindtree** [comment]
Okydoke, gonna merge this :+1: Will address the other stuff above at a future date.

**Comment by mitchmindtree** [comment]
Published as **0.5.0**.

**Comment by yupferris** [comment]
Didn't have a chance to look at this until now, but it looks fantastic! I'll play around and test with it a bit more later today. Great stuff!

**Comment by yupferris** [comment]
Played around with it, this feels a lot better to use, and the possible runtime errors are still quite predictable and safe. Awesome job!

**Pull request merged**
